package uz.o_rustamov.readium.enums;

public enum Permission {

    ADD_USER,
    DELETE_USER,
    EDIT_USER,
    VIEW_USERS,

    ADD_ROLE,
    VIEW_ROLES,
    EDIT_ROLE,
    DELETE_ROLE,

    EDIT_STUDY_CENTRE,
    VIEW_STUDY_CENTRES,
    ADD_STUDY_CENTRE,
    DELETE_STUDY_CENTRE,

//    VIEW_NOTIFICATIONS,
//    DELETE_NOTIFICATION,

    DELETE_NEWS,
    ADD_NEWS,
    ACTIVATE_NEWS,

    VIEW_GROUPS,
    ADD_GROUP,
    EDIT_GROUP,
    DELETE_GROUP,

    VIEW_SUBJECTS,
    ADD_SUBJECT,
    EDIT_SUBJECT,
    DELETE_SUBJECT,

    VIEW_STUDENT_COURSES,
    ATTACH_STUDENT_TO_GROUP,
    REMOVE_STUDENT_FROM_GROUP,

    ADD_ASSIGNMENT,
    EDIT_ASSIGNMENT,

    VIEW_GRADES,
    ASSESS_STUDENT,

    VIEW_PAYMENTS,
    DELETE_PAYMENT,
    CREATE_PAYMENT,

}
